---
# Enable automatic installation of security updates.
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Enable periodic update + unattended upgrade
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

- name: Ensure the unattended-upgrades service is enabled and running
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started
